spring:
  application:
    name: estoque
  datasource:
    url: jdbc:postgresql://localhost:5432/supermercado
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
     enabled: true
     locations: classpath:db/migration

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterAccess=30m
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    br.com.supermercado.estoque: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

app:
  database:
    pool:
      max-size: 10
      min-idle: 2
      max-lifetime: 300000