# Bloco único contendo todos os serviços
services:

  #-----------------------------------------
  # SERVIÇOS DA APLICAÇÃO "SUPERMERCADO"
  #-----------------------------------------

  # Serviço do banco de dados PostgreSQL para a aplicação
  postgres_supermercado:
    image: postgres:15
    container_name: postgres_supermercado_estoque_container
    environment:
      # Credenciais para o banco da sua aplicação
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin@123
      POSTGRES_DB: supermercado
    ports:
      # Expõe a porta 5432 no seu computador para a sua aplicação Spring Boot conectar em "localhost:5432"
      - "5432:5432"
    volumes:
      # Volume nomeado para persistir os dados do banco da aplicação
      - supermercado_db_data:/var/lib/postgresql/data
      # Mapeia uma pasta local para scripts de inicialização (opcional)
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

  #-----------------------------------------
  # SERVIÇOS DO SONARQUBE
  #-----------------------------------------

  # Serviço principal do SonarQube
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_container
    ports:
      - "9000:9000" # Porta de acesso à interface web do SonarQube
      - "9092:9092"
    environment:
      # Configurações de conexão para o banco de dados do SonarQube
      - SONAR_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      # Volumes nomeados para persistir dados, plugins e logs do SonarQube
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      # Garante que o banco de dados do SonarQube inicie antes
      - sonarqube_db
    restart: unless-stopped

  # Serviço do banco de dados PostgreSQL para o SonarQube
  sonarqube_db:
    image: postgres:15
    container_name: sonarqube_db
    environment:
      # Credenciais para o banco do SonarQube (devem ser as mesmas da configuração acima)
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      # Volume nomeado para persistir os dados do banco do SonarQube
      - sonarqube_db_data:/var/lib/postgresql/data
    restart: unless-stopped
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  #-----------------------------------------
  # SERVIÇOS DO KAFKA
  #-----------------------------------------

  # Serviço principal do Kafka
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# Bloco único declarando todos os volumes nomeados
volumes:
  # Volume para o banco da aplicação
  supermercado_db_data:

  # Volumes para o SonarQube e seu banco de dados
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db_data:
